### ISSUE TITLE
Silent disk preparation failures

### ISSUE THREAD

**Issue by vosmann** [zalando-stups/taupage#109]
Hello, 
When starting up an instance with bad disk configuration, it's possible to get an error such as:
```
Aug  3 15:33:25 ip-172-31-151-222 taupage-init: ERROR: Failed to start 10-prepare-disks.py
```
This causes the Docker image to never get started, therefore resulting in a live instance, but stuck in a non-usable limbo without an error message or rollback attempt.

**Comment by vosmann** [comment]
Senza creation then hangs at autoscaling group creation. Stays at:
```
some-name 1 AutoScaling::AutoScalingGroup  some-cluster  CREATE_IN_PROGRESS Resource creation Initiated  15m ago
```
Not sure if this is intended behaviour.

**Comment by femueller** [comment]
The problem is that basically if the disk configuration does not work as expected. The entire instance won't boot according to the expectation.
The Docker container also won't start, because of a missing dependency (mounting a disk) and the health check fails, so the autoscaling group also won't become successful, because the Docker container was never booting, cause of failed conditions.

So actually the behaviour should be all right or do you have any recommendations?
