### ISSUE TITLE
Consistent paths to monitoring agents within containers

### ISSUE THREAD

**Issue by marek-obuchowicz** [zalando-stups/taupage#127]
At the moment we have two monitoring agents exposed to the containers: newrelic jvm agent (`/data/newrelic`) and appdynamics (`/agents/appdynamics-jvm`). We should use consistent paths for the agents. As appdynamics is at the moment being tested and not yet widely used, i propose to change appdynamics mountpoint from `/agents/appdynamics-jvm` to `/data/appdynamics`

**Comment by hjacobs** [comment]
I haven't checked this, but if the paths are inconsistent: :+1:

**Comment by sarnowski** [comment]
2 things for that:

1.) Using `/data` is as bad as `/things`, `/stuff`, `/util`, ... you get the gist. Its a bad practice to name something like that because you just don't know what its for. Thats why we chose `/agents` for the integration as this is much more descriptive what to expect in there.
2.) We have more users using AppDynamics which makes migrating harder. We should mount `/agents/newrelic` in addition to `/data/newrelic` and make a clear deprecation warning to the users, so that we are able to remove `/data/newrelic` in the near future.

**Comment by femueller** [comment]
According to @apfeiffer85 this is fixed.
