### ISSUE TITLE
Implementation of root config option in presence of USER directive in Dockerfile

### ISSUE THREAD

**Issue by a1exsh** [zalando-stups/taupage#165]
Hey,

I've been trying to run a Docker image with Apache2 as the main process under taupage.  The problem I'm running into is that taupage overrides the user on `docker` command line, even though I have a `USER www-data:www-data` directive in my `Dockerfile`.

In the end, when started under taupage, the run script in my Docker image can't update a configuration file (which is owned by `www-data`) and the web server can't be started properly.  I can work around this problem by using `root: true` in taupage config.

But that actually doesn't give `root`, it just doesn't override the user, so I think either this config option needs to be renamed (e.g. `no_user_override: false`) or its implementation should pass `-u 0` to docker when it is enabled (now it's the other way round: if not enabled, `-u <uid of user 'application'>` is added).

By the way, why a custom unprivileged user when we have the standard `nobody:nogroup`?..

**Comment by sarnowski** [comment]
I don't think there is anything wrong here. Yes, by default we enforce that the application runs as an unprivileged user.  As long as Docker does not provide proper user namespace support, this will not change.

`root: true` does exactly what it says: it runs the container as root. If you drop root privileges with the `USER` statement or drop privileges with any other technique is up to you and our of control for us.

Using `nobody` is bad practice as this user should have no privileges at all on a system so that daemons that drop to it cannot do anything with its privileges. Using that for the application is bad as then all other nobody daemons would have much more control over the actual important application with its secrets.

**Comment by hjacobs** [comment]
I agree with @sarnowski on this topic. The user namespace support in Docker will eventually fix many of these current problems.
