### ISSUE TITLE
Scalyr agent should follow log files

### ISSUE THREAD

**Issue by nsorger** [zalando-stups/taupage#402]
Currently if a log file rotates the Scalyr agent doesn't pick it up anymore. This leads to corner cases where the Scalyr agent can't read the last log lines in the "current" application.log.

The Scalyr agent should follow the log files to prevent that from happening.

**Comment by apfeiffer85** [comment]
The Current Scalyr Agent configuration only supports "latest log lines" so the agent will not follow from the beginning of the log file. 

So logrotate "rotates" the logfile because of the size and afterwards the Scalyr agent restarts. 
And within that restart time the new application.log is already filling up with logs because of the high traffic. 
But the Agent is only able to pick up the latest log lines after restart. So therefore it can be that you will loose  some log lines. 

There is a easy solution for that, because now the latest Scalyr agent support's also to read the file from the beginning. 
We only have to adjust the Scalyr agent config. 

`"copy_from_start": true`
